### ISSUE TITLE
Use conda-lock for qgreenland command environment

### ISSUE THREAD

**Issue by trey-stafford** [nsidc/qgreenland#548]
We now use `conda-lock` for our main `qgreenland` conda environment. We still use an `environment.yml`-style file for our "command" environment, however (the environment where dataset transformations take place in, with e.g., `gdal` installed). 

https://github.com/nsidc/qgreenland/pull/547/files#r1224751677

**Comment by mfisher87** [comment]
I do think we should be locking the command environment.

Just want to clear up a few things: We also still have an `environment.yml` file for the main environment. The only file that was replaced was the old `conda env export`-style lockfile `environment-lock.yml` and it was replaced 1:1 with `conda-lock.yml`. Since there was no lockfile for the command environment, I didn't want to add one to keep my change focused on migrating to `conda-lock`.

**Comment by trey-stafford** [comment]
Related: https://github.com/nsidc/qgreenland/issues/595
