### ISSUE TITLE
Consider renaming "online" layer terminology

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/qgreenland#655]
"Remote" layers instead?

All the layers are online in some way (http/cmr/manual). So maybe "remote" is a better way to label our "gdal remote"/wms/wfs/wcs layers.

Twila: Or something like "remotely-hosted".

**Comment by twilamoon-science** [comment]
I think the group name "Internet-required data" is solid. Descriptive and should continue to describe any subgroup/layers within it. I'd be OK closing this.

**Comment by MattF-NSIDC** [comment]
@trey-stafford I'm struggling to remember with this issue; was this an idea for an internal code naming change? I don't think it was for the naming in the Layers Panel. I should have been more clear when I opened this... :frowning_face:

**Comment by trey-stafford** [comment]
That's a good question. My immediate impression was that this was aimed at the layer group naming. Maybe we intended to aim this at re-thinking terminology around [online assets](https://qgreenland.readthedocs.io/en/latest/contributor/reference/api/models.html#qgreenland.models.config.asset.OnlineAsset)? 

Given the ambiguity and question around action on this, I would agree with closing.

**Comment by trey-stafford** [comment]
Actually, thinking about this again - I realize that we must have meant the model around online assets.

I think the mention of "gdal_remote" is OBE. The original description here was referring to the fact that most of our assets come from the internet (e.g., an `HttpAsset` is obtained from an online resource), but our `OnlineAsset` is really just a reference to a layer hosted online & accessed through a service instead of from data stored on disk.

The handling of the term "online" is a bit messy in the code too. For example, we have a function called `vector_or_raster` that is typed to return one of "Raster", "Vector", or "Online", but our mapping from provider -> layer type doesn't include "Online", so `vector_or_raster` will only return what it's function name indicates - "Vector" or "Raster".

The only place we appear to use the "Online" `QgsLayerType` is in the `export` code that produces the layer csv. This puts "Online" in the "Vector or Raster" column for online layers! That seems confusing. Maybe a separate field for "On disk" that is true/false would be a better indicator. Online assets are still either vectors or rasters! 

Draft PR to partially resolve this issue here: https://github.com/nsidc/qgreenland/pull/728
